# Generated by Django 3.2.15 on 2024-08-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20240814_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('CONFIRMATION', 'На подтверждении'), ('ASSEMBLED', 'Собран'), ('ON_WAY', 'В пути'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], db_index=True, default='UNPROCESSED', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
