# Generated by Django 3.2.15 on 2024-08-13 22:18

from django.db import migrations


class Migration(migrations.Migration):
    def set_product_price(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.prefetch_related('product').iterator():
            item.price = item.product.price
            item.save()

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_product_price),
    ]
