# Generated by Django 3.2.15 on 2024-08-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_orderdetail_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
    ]
