# Generated by Django 3.2.15 on 2024-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_orderdetail_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('CONFIRMATION', 'Готовится'), ('ASSEMBLED', 'Собран'), ('ON_WAY', 'В пути'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], db_index=True, default='UNPROCESSED', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
