# Generated by Django 3.2.15 on 2024-09-05 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_orderdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='registrated_at',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Зарегистрирован в'),
        ),
    ]
